### ISSUE TITLE
not compatible with current Helib

### ISSUE THREAD

**Issue by kzhong130** [iliailia/comparison-circuit-over-fq#2]
Hi there, thanks for open sourcing your implementations, I really appreciate that. However, when I tried out this code, I installed Helib from their [git repo](https://github.com/homenc/HElib), seems this violate your requirement in your [cmake](https://github.com/iliailia/comparison-circuit-over-fq/blob/master/code/CMakeLists.txt#L13) file that helib should be using exactly 2.0.0. Thus I changed this line to `find_package(helib)`, and it compiled correctly. 

I tried to run the example you gave `./comparison_circuit B 7 2 300 90 3 10 y`, but it showed segmentation fault which seems to be inside NTL lib? This is my gdb output `Program received signal SIGSEGV, Segmentation fault.
0x000055555558cce2 in NTL::Vec<NTL::ZZ_pE>::operator[](long) ()`. I guess this is due to that I do not use 2.0.0 helib? But seems that i cannot find the old version of helib from their git repo. Could you please take a look at this? Thank you very much!

**Comment by iliailia** [comment]
Hi,

thanks for the comment. The problem wasn't in HElib, but in some line in the code commented out for no good reason. Check the update out and let me know if you still have problems.

**Comment by kzhong130** [comment]
Thank you!
