### ISSUE TITLE
Test code shows 'helib::LogicError' Decrypting with too much noise 

### ISSUE THREAD

**Issue by JinseongP** [iliailia/comparison-circuit-over-fq#3]
Hi, I'm trying to use your sample code below,
./comparison_circuit B 7 2 300 90 3 10 y
But it shows 'helib::LogicError' Decrypting with too much noise in Helib 2.1.0. (also in 2.0.0)
Could you check this?
Thanks.

**Comment by iliailia** [comment]
Hi,

the parameters you're using (log q=90 for d=2, l=3 using the notation from the paper) are too small. This is why you get a noise overflow. If you switch to log q=170 (./comparison_circuit B 7 2 300 170 3 10 y), the program works just fine.
